name: Python application
on: [push, pull_request]
permissions:
  contents: read
jobs:
  Python-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Test with pytest
        run: |
          export PYTHONPATH=src
          pytest
  Docker-Container:
    runs-on: ubuntu-latest
    container: node:19.8.1
    steps:
      - name: Test the node version
        run: |
          node --version
          npm --version

  Groovy-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install -y groovy
      - name: Import Groovy library
        run: |
          echo "Groovy Library imported"
      - name: Run Groovy script
        run: |
          groovy tests/file.groovy
